### ISSUE TITLE
NameError: name 'RawNetWithCgging' is not defined

### ISSUE THREAD

**Issue by happyjin** [kimho1wq/SegmentAggregation#1]
Thanks for your awesome project! I encounter a problem when I try to train the model. I think this function is not defined. Could you please upload this function? Thanks in advance!

**Comment by kimho1wq** [comment]
I think it will work if you change 'RawNetWithCgging' to 'RawNetWithSA'

**Comment by happyjin** [comment]
Thanks for your reply which is helpful!
